name: thematic
channels:
  - conda-forge
  - default
dependencies:
  - python=3.7
  - pip
  - pip:
      - mlflow>=1.6.0
      - statsmodels==0.11.1
      - scikit-learn==0.22.1
      - pandas>=1.3.3
      - logging>='0.5.1.2
      - time
      - numpy>=1.19.5
      - scipy>=1.6.0
      - yfinance>=0.1.63
      - click>=8.0.3
      - matplotlib>=3.4.2
      - nltk>=3.6.5
      - textblob>=0.15.3
      - dask>=2021.08.1
      - random
      - wordcloud>=1.8.0
      - requests>=2.23.0
      - cloudpickle==2.0.0
      - typing-extensions==3.10.0.2
      - argparse==1.4.0
      - lz4==3.1.3
      - psutil==5.8.0
      